services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Netresearch\NrImageOptimize\:
    resource: '../Classes/*'

  Netresearch\NrImageOptimize\Processor:
    arguments:
      $imageManager: !service
        class: Intervention\Image\ImageManager
        arguments:
          - !service
            class: Intervention\Image\Drivers\Imagick\Driver

  Netresearch\NrImageOptimize\Controller\MaintenanceController:
    public: true

  Netresearch\NrImageOptimize\EventListener\OptimizeOnUploadListener:
    tags:
      - name: event.listener
        identifier: 'nr_image_optimize.optimize_on_upload.added'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileAddedEvent
        method: optimizeAfterAdd
      - name: event.listener
        identifier: 'nr_image_optimize.optimize_on_upload.replaced'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileReplacedEvent
        method: optimizeAfterReplace
