services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Netresearch\NrImageOptimize\:
    resource: '../Classes/*'

  Netresearch\NrImageOptimize\Processor:
    arguments:
      $imageManager: !service
        class: Intervention\Image\ImageManager
        arguments:
          - !service
            class: Intervention\Image\Drivers\Imagick\Driver

  Netresearch\NrImageOptimize\Controller\MaintenanceController:
    public: true
