services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Netresearch\NrImageOptimize\:
    resource: '../Classes/*'

  Intervention\Image\ImageManager:
    factory:
      - '@Netresearch\NrImageOptimize\Service\ImageManagerFactory'
      - 'create'

  Netresearch\NrImageOptimize\Service\ImageReaderInterface:
    alias: Netresearch\NrImageOptimize\Service\ImageManagerAdapter

  Netresearch\NrImageOptimize\ProcessorInterface:
    alias: Netresearch\NrImageOptimize\Processor

  Netresearch\NrImageOptimize\Controller\MaintenanceController:
    public: true
