name: CI

on:
  push:
    branches:
      - main
      - develop
      - TYPO3-13
  pull_request:
    branches:
      - main
      - develop
      - TYPO3-13

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.2'
          - '8.3'
          - '8.4'
        include:
          - php-version: '8.2'
            typo3-version: '^13.0'
          - php-version: '8.3'
            typo3-version: '^13.0'
          - php-version: '8.4'
            typo3-version: '^13.0'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, json, dom, curl, xml, zip, opcache, gd
          tools: composer:v2
          coverage: none

      - name: Validate composer.json
        run: composer validate --strict

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-

      - name: Install dependencies
        run: |
          composer require typo3/cms-core:${{ matrix.typo3-version }} --no-update
          composer update --prefer-dist --no-progress

      - name: Run PHP CS Fixer
        run: composer ci:test:php:cgl

      - name: Run PHPLint
        run: composer ci:test:php:lint

      - name: Run PHPStan
        run: composer ci:test:php:phpstan

      - name: Run Rector
        run: composer ci:test:php:rector

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, json, dom, curl, xml, zip, opcache, gd
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run all tests
        run: composer ci:test

  compatibility-check:
    name: PHP Compatibility Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '8.2'
          - '8.3'
          - '8.4'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, json
          tools: none
          coverage: none

      - name: Check PHP ${{ matrix.php-version }} syntax compatibility
        run: |
          echo "Checking PHP ${{ matrix.php-version }} compatibility for TYPO3 13..."
          errors=0
          
          # Check Classes directory
          if [ -d "Classes" ]; then
            echo "Checking Classes directory..."
            while IFS= read -r file; do
              if ! php -l "$file" > /dev/null 2>&1; then
                echo "Syntax error in: $file"
                php -l "$file"
                errors=$((errors + 1))
              fi
            done < <(find Classes -name "*.php" -type f)
          fi
          
          # Check Configuration directory
          if [ -d "Configuration" ]; then
            echo "Checking Configuration directory..."
            while IFS= read -r file; do
              if ! php -l "$file" > /dev/null 2>&1; then
                echo "Syntax error in: $file"
                php -l "$file"
                errors=$((errors + 1))
              fi
            done < <(find Configuration -name "*.php" -type f)
          fi
          
          # Check root PHP files if they exist
          for file in *.php; do
            if [ -f "$file" ]; then
              if ! php -l "$file" > /dev/null 2>&1; then
                echo "Syntax error in: $file"
                php -l "$file"
                errors=$((errors + 1))
              fi
            fi
          done
          
          if [ $errors -eq 0 ]; then
            echo "✅ All PHP files are compatible with PHP ${{ matrix.php-version }} and TYPO3 13"
          else
            echo "❌ Found $errors file(s) with syntax errors"
            exit 1
          fi
