name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
        include:
          - php-version: '8.1'
            typo3-version: '^11.5'
          - php-version: '8.2'
            typo3-version: '^12.0'
          - php-version: '8.3'
            typo3-version: '^12.0'
          - php-version: '8.4'
            typo3-version: '^12.0'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, json
          tools: composer:v2
          coverage: none

      - name: Validate composer.json
        run: composer validate --strict

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-

      - name: Install dependencies
        run: |
          composer require typo3/cms-core:${{ matrix.typo3-version }} --no-update
          composer update --prefer-dist --no-progress

      - name: Run PHP CS Fixer
        run: composer ci:test:php:cgl

      - name: Run PHPLint
        run: composer ci:test:php:lint

      - name: Run PHPStan
        run: composer ci:test:php:phpstan

      - name: Run Rector
        run: composer ci:test:php:rector

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, json
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run all tests
        run: composer ci:test

  compatibility-check:
    name: PHP 8.4 Compatibility Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl, json
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --ignore-platform-reqs

      - name: Check PHP 8.4 compatibility
        run: |
          echo "Checking PHP 8.4 compatibility..."
          php -l Classes/**/*.php
          php -l Configuration/**/*.php
